---
- name: "Check if the project is already cloned."
  stat: "path={{ drupal_project_path.stdout }}/.git"
  register: drupal_project_cloned_status

- name: "Check if the project destination directory is already there."
  stat: "path={{ drupal_project_path.stdout }}"
  register: drupal_project_destination_status

- name: "Download Drupal from Git repository. This may take a few minutes..."
  git: >
    repo={{ drupal_source }}
    version={{ drupal_version }}
    update=no
    accept_hostkey=yes
    dest={{ drupal_project_path.stdout }}
  register: drupal_project_cloned_status
  when: drupal_project_cloned_status.stat.exists == false

# - name: "Drupal is installed (not running), is a fact."
#   set_fact: "drupal_is_installed"
#   when: drupal_project_cloned_status.rc != 0
